<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Welcome extends CI_Controller {

	/**
	 * Index Page for this controller.
	 *
	 * Maps to the following URL
	 * 		http://example.com/index.php/welcome
	 *	- or -  
	 * 		http://example.com/index.php/welcome/index
	 *	- or -
	 * Since this controller is set as the default controller in 
	 * config/routes.php, it's displayed at http://example.com/
	 *
	 * So any other public methods not prefixed with an underscore will
	 * map to /index.php/welcome/<method_name>
	 * @see http://codeigniter.com/user_guide/general/urls.html
	 */
         /*public function __construct() {
             parent::__construct();
             echo "This is generated by the __construct function!";
         }*/
    
	public function index()
	{
		$this->load->view('welcome_message');
	}
        
        public function what($p1, $p2)
	{
		echo "The params passed are: $p1 and $p2";
	}
        
        public function test()
        {
                $this->load->model("hello_model");
                $fbprofile = $this->hello_model->getFbSession();
                
                //$this->load->view('header');
                //$data = array("name" => $name);
                //$data["profile"] = $profile;
                //$this->load->view('testView', $data);
        }
}

/* End of file welcome.php */
/* Location: ./application/controllers/welcome.php */